### ISSUE TITLE
Feature - Genital change

### ISSUE THREAD

**Issue by ahuhftg** [NickWildish/Mas-NSFW-Submod#101]
PLEASE add an option to change genitalia after telling Monika what you have. I picked the wrong option and then backed up her persistent and I have no idea how to change this.

**Comment by NickWildish** [comment]
You should be able to do this. If you look under 'Repeat Conversation' -> 'Sex', there should be a topic called '[player]'s Genitalia'. Run this topic to change your genitalia.

**Comment by NickWildish** [comment]
Closing as I haven't gotten a response back.
