### ISSUE TITLE
Bug - Monika won't lean with underwear or outfit

### ISSUE THREAD

**Issue by SaltyMelonLord** [NickWildish/Mas-NSFW-Submod#114]
I was always wondering why Monika wouldn't lean when wearing her underwear or nothing at all. First I thought this was intentional, but since she does normally with lingerie from other submods, I wanted to change that, and it turned out there is a bug in nsfw_birthday_suit.rpy:

Code (see comment):
`mas_clothes_birthday_suit = MASClothes(`
        `"birthdaysuit",`
        `"birthdaysuit",`
        `MASPoseMap(`
            `default=True,`
            `user_reg_for_1=True, # bug: must be "use_reg_for_l=True"`
       ` ),`
        `stay_on_start=True,`
        `ex_props={`
            `store.mas_sprites.EXP_C_LING: True,`
        `},`
        `pose_arms=MASPoseArms({}, def_base=False)`
    `)`
All the underwear has the same bug. Fixing it will make Monika change poses normally.

**Comment by NickWildish** [comment]
Thanks for letting me know. I've made the necessary changes in the dev branch.

**Comment by SaltyMelonLord** [comment]
It’s still wrong in the update. It has to be "use_reg_for_l" with the last character being a small l like in "love Monika", not a 1.
