### ISSUE TITLE
Bug - Monika disappears for a line during the masturbation brb return.

### ISSUE THREAD

**Issue by ML-Gaming** [NickWildish/Mas-NSFW-Submod#116]
Monika disappears for a line during the brb return section.

**To Reproduce**
1. Go to 'Be Right Back
2. Click on 'I'm going to masturbate while not Enamoured'
3. See error at the line 'm 6euafb "Now that you're done with...{i}that{/i}..."'

**Expected behavior**
Monika shouldn't disappear when saying this line.

**Screenshots**
![screenshot0005](https://github.com/NickWildish/Mas-NSFW-Submod/assets/108233048/39c319af-04ce-44ec-942d-80d42e09340d)

This appears to be a problem with the sprite code as the individual parts of the code work just not when put together in this order. The code 'm 6eubfa' is similar and correctly displays a sprite while being similar to the original line.

**Comment by NickWildish** [comment]
Yup, appears to be an issue with 'fb' being put before 'a' which caused the issue. Will promptly fix, though I'll be replacing it with 6hkbfb so the dialogue suits better.

**Comment by NickWildish** [comment]
I believe this has been fixed, but do let me know if that is not the case.
