### ISSUE TITLE
Typo - "dansel in distress"

### ISSUE THREAD

**Issue by ZeitHeld** [NickWildish/Mas-NSFW-Submod#126]
When talking about the history of bondage, there is a slight typo, where `damsel` is misspelled as `dansel`
The same typo has been made in the line after _(or where ever it was mentioned again)_
![screenshot0175](https://github.com/NickWildish/Mas-NSFW-Submod/assets/76132257/12484236-ca41-43fc-8570-3151697264d0)

**Comment by NickWildish** [comment]
This has been resolved in the latest update.
