### ISSUE TITLE
Feature - Going away to mastrubate

### ISSUE THREAD

**Issue by GiletteOnPH** [NickWildish/Mas-NSFW-Submod#27]
A nice feature to add would be a new reason to the "Be right back..." interaction. The reason could be "Im going to mastrubate".
Monika may ask the player to stay and do it together - and if not may ask the player to think about her while doing it.

**Comment by TreeWizard96** [comment]
https://github.com/TreeWizard96/Mas-NSFW-Submod/tree/mast-topic-wip

**Comment by TreeWizard96** [comment]
I think we can mark this as closed or implemented now

**Comment by NickWildish** [comment]
Yeah, fair call. Marking as closed.
