### ISSUE TITLE
Feature - Erotic Stories

### ISSUE THREAD

**Issue by GiletteOnPH** [NickWildish/Mas-NSFW-Submod#29]
A nice feature would be to add erotic stories to the "Can you tell me a story?" interaction, since Monika likes literature.

**Comment by NickWildish** [comment]
Have also added erotic stories framework as well. Just need to add some story templates and let people start implementing their own.

**Comment by NickWildish** [comment]
Think we can say this topic has been successfully implemented. Closing as completed.
