### ISSUE TITLE
Feature - Erotic Compliments

### ISSUE THREAD

**Issue by GiletteOnPH** [NickWildish/Mas-NSFW-Submod#30]
A nice feature for the NSFW Submod could be the player complimenting Monika for erotic reasons under the Romance > "I want to tell you something..." section. These compliments may include: "I love your breasts", "I love your dirty talk", "You make me hard".

**Comment by SorcererPug** [comment]
The framework has been added for compliments now, thanks to Dargon. We've added a few basic compliments in there now, but once they're complete and poses have been added, we can consider this finished, and allow the community to add their own.

**Comment by NickWildish** [comment]
The framework has been added for compliments now, thanks to Dargon. We've added a few basic compliments in there now, but once they're complete and poses have been added, we can consider this finished, and allow the community to add their own.

**Comment by NickWildish** [comment]
Compliments have now been implemented. Closing as complete.
