### ISSUE TITLE
game crashes upon requesting to hear an erotic story

### ISSUE THREAD

**Issue by my-otter-self** [NickWildish/Mas-NSFW-Submod#63]
hello! title related, traceback below~

> [code]
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/script-ch30.rpy", line 1513, in script call
>   File "game/event-handler.rpy", line 2534, in script call
>   File "game/Submods/NSFW Submod/nsfw_stories.rpy", line 273, in script
>     if inspired_monika == True:
>   File "game/Submods/NSFW Submod/nsfw_stories.rpy", line 273, in <module>
>     if inspired_monika == True:
> NameError: name 'inspired_monika' is not defined
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/script-ch30.rpy", line 1513, in script call
>   File "game/event-handler.rpy", line 2534, in script call
>   File "game/Submods/NSFW Submod/nsfw_stories.rpy", line 273, in script
>     if inspired_monika == True:
>   File "E:\jogos\JUST MONIKA\MY SIGNIFICANT OTTER\MOMO\renpy\ast.py", line 1656, in execute
>     if renpy.python.py_eval(condition):
>   File "E:\jogos\JUST MONIKA\MY SIGNIFICANT OTTER\MOMO\renpy\python.py", line 1749, in py_eval
>     return py_eval_bytecode(code, globals, locals)
>   File "E:\jogos\JUST MONIKA\MY SIGNIFICANT OTTER\MOMO\renpy\python.py", line 1743, in py_eval_bytecode
>     return eval(bytecode, globals, locals)
>   File "game/Submods/NSFW Submod/nsfw_stories.rpy", line 273, in <module>
>     if inspired_monika == True:
> NameError: name 'inspired_monika' is not defined
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.12.8
> [/code]

**Comment by mizuotanu-nirera** [comment]
Can you tell me if [this](https://github.com/mizuotanu-nirera/mas-nsfw-submod/blob/main/game/Submods/NSFW%20Submod/nsfw_stories.rpy) updated `nsfw_stories.rpy` fixes the issue for you? (Right click "Raw" and "Save link as..." to your NSFW submod folder.)

**Comment by my-otter-self** [comment]
yes, it worked! thank you very much. and sorry for the delay! ehehe~

**Comment by mizuotanu-nirera** [comment]
No problem. Since the fix worked for you I'll make a PR.
