### ISSUE TITLE
error when acessing other girls' nsfw stories

### ISSUE THREAD

**Issue by my-otter-self** [NickWildish/Mas-NSFW-Submod#72]
hello! i faced this error when accessing the other girls erotic stories, part 1. did i do something wrong? thank youuu~

> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
>   File "game/script-ch30.rpy", line 1513, in script call
>   File "game/event-handler.rpy", line 2534, in script call
>   File "game/Submods/NSFW Submod/nsfw_dokistories.rpy", line 102, in script
>     if not renpy.seen_label(nsfw_monika_erotic_stories_init):
>   File "game/Submods/NSFW Submod/nsfw_dokistories.rpy", line 102, in <module>
>     if not renpy.seen_label(nsfw_monika_erotic_stories_init):
> NameError: name 'nsfw_monika_erotic_stories_init' is not defined
> 
> -- Full Traceback ------------------------------------------------------------
> 
> Full traceback:
>   File "game/script-ch30.rpy", line 1513, in script call
>   File "game/event-handler.rpy", line 2534, in script call
>   File "game/Submods/NSFW Submod/nsfw_dokistories.rpy", line 102, in script
>     if not renpy.seen_label(nsfw_monika_erotic_stories_init):
>   File "E:\jogos\JUST MONIKA\MY SIGNIFICANT OTTER\MOMO\renpy\ast.py", line 1656, in execute
>     if renpy.python.py_eval(condition):
>   File "E:\jogos\JUST MONIKA\MY SIGNIFICANT OTTER\MOMO\renpy\python.py", line 1749, in py_eval
>     return py_eval_bytecode(code, globals, locals)
>   File "E:\jogos\JUST MONIKA\MY SIGNIFICANT OTTER\MOMO\renpy\python.py", line 1743, in py_eval_bytecode
>     return eval(bytecode, globals, locals)
>   File "game/Submods/NSFW Submod/nsfw_dokistories.rpy", line 102, in <module>
>     if not renpy.seen_label(nsfw_monika_erotic_stories_init):
> NameError: name 'nsfw_monika_erotic_stories_init' is not defined
> 
> Windows-8-6.2.9200
> Ren'Py 6.99.12.4.2187
> Monika After Story 0.12.8

`

**Comment by NickWildish** [comment]
Found the bug. I had forgotten to quote the label name on line 102.
Please redownload the dokistories.rpy and confirm that it works on your end as well.

**Comment by my-otter-self** [comment]
can i get a link for the dokistories.rpy file please? c:

**Comment by my-otter-self** [comment]
got it! thanks a bunch. i'll close this for now, since it fixed the problem! :)
