### ISSUE TITLE
Bug - Monika writes out [naughty_bits] 

### ISSUE THREAD

**Issue by d3adpan** [NickWildish/Mas-NSFW-Submod#78]
**Describe the bug**

Sometimes during naughty flirting, Monika writes out [naughty_bits] rather than saying the intended line.

**To Reproduce**

1. Go to the 'Sex' tab
2. Click on 'I want to tell you something lewd'
3. Scroll down to an option you previously selected, and choose it again.
4. The dialogue sometimes ends with [naughty_bits]

**Expected behavior**

I expected to read a line of normal text

**Screenshots**

![screenshot0844](https://user-images.githubusercontent.com/61102477/176808652-1b05e02a-65c5-4049-b5be-3e2ad920531f.png)

**Comment by mizuotanu-nirera** [comment]
Thanks for your detailed bug report.

Can you try replacing `nsfw_compliments.rpy` in your submod folder with [this](https://github.com/mizuotanu-nirera/mas-nsfw-submod/blob/main/game/Submods/NSFW%20Submod/nsfw_compliments.rpy) version and see if the issue still persists? (Right click the "Raw" button and "Save link as...")

**Comment by d3adpan** [comment]
Thank you, I just downloaded the .rpy listed above, will test within the hour

**Comment by d3adpan** [comment]
Closing as solved, thank you dev team
