### ISSUE TITLE
Feature - Monika asking to sext/engage in other activities

### ISSUE THREAD

**Issue by DatBoiwhoposts** [NickWildish/Mas-NSFW-Submod#79]
I'm loving the progress this mod is making currently but feel weird being the one always asking to do lewd things. I think it would be really cool if after a certain amount of time without sexting (or engaging in other lewd activities the mod adds later) Monika would ask to do things with the player provided her affection is already high (like 2000 or something.) She could start out shy about asking and build up to being comfortable with her need for physical intimacy. The timer for her asking to do things with the player could decrease with more intimate contact like holding or kissing her. This would allow the sexual interactions of the mod to feel more two sided as a whole with both parties making requests of one another instead of just the player taking the lead constantly.

Upon her asking the player to engage in a sexual act the player could:

Say yes, and begin the normal sext dialogue (or other dialogues implemented later she asks for). Similar to telling her you feel horny, but instead its her telling you she feels horny basically.

Tell her no you don't feel up to it right now which would reset her timer for asking and if you say no enough maybe prompt conversation to pop asking if you just don't want her asking anymore.

Tell her you're busy right now but when you get a chance you'll do whatever she wanted to do with her. This would add a little bit of extra dialogue to the initial conversation of whatever she wanted to do. (for example, If she wanted to sext and you choose to sext it would add dialogue of her talking about how shes been waiting for you and been trying not to touch herself until you were ready) and if you choose to do something else lewd instead she might remind you of your promise and ask you again, from there you could say you'd rather do what you selected. To which she'll pretend to pout for a moment and say something like "alright but next time I wanna do X" Alternatively you could say "You're right I did say that, and X sounds better anyway" to which she could blush and smile and reply with "I was hoping you'd say that lets get started" at which point the normal dialogue for whatever activity she wanted to do would begin.

**Comment by NickWildish** [comment]
This sounds like a great feature. I'll add this to our next milestone.

**Comment by NickWildish** [comment]
Monika can now do this in our dev branch. Closing as completed and will be pushed in version 1.3.0.
