### ISSUE TITLE
Bug - Always get the first event sexting response

### ISSUE THREAD

**Issue by d3adpan** [NickWildish/Mas-NSFW-Submod#80]
**Describe the bug**
After multiple sexting sessions, Monika continues to refer to it as her first time; ie: being kind of  nervous and not knowing what to expect

**To Reproduce**
1. Go to the ''I feel...' tab
2. Click on '...horny'
3. Select 'Yes'
4. Continue to the countdown and finish together.
5. Wait anywhere from a few hours to 2 days.
6. Repeat above steps and she is again nervous about her first time.

**Expected behavior**
I expected the dialogue would move on to  "I remember the last time we did this; it was so much fun!"
"So [player]... Let's get started, shall we?"

**Screenshots**
I'm not sure if it would help, but I will provide one if needed

**Comment by d3adpan** [comment]
It should be noted that this happened before I got the 'Do you want to sext?' option under the 'Sex' tab.  After receiving that option and completing the first run, everything behaves as expected.  So maybe not a bug, perhaps just have the '...horny' option appear at the same time as the 'Do you want to sext' option?

**Comment by mizuotanu-nirera** [comment]
Many thanks for the detailed bug report and figuring out this edge case we missed. I believe [this](https://github.com/mizuotanu-nirera/mas-nsfw-submod/blob/main/game/Submods/NSFW%20Submod/nsfw_sexting.rpy) will fix the issue though of course that is hard to test directly.

**Comment by d3adpan** [comment]
I may have a slightly older MAS installation on my old netbook, I can take a look when I get back home - been on the road for the last week or so.  Figure by the weekend I should be back local.  Affection should be high enough to give it a try.  Thanks!

**Comment by d3adpan** [comment]
Looks like everything is behaving as expected.  Restored a game from 2020.  Ran through the first event through the "I feel ...horny" option, waited a day and ran through it again the same way, she remembers the first event.  Thank you!
