### ISSUE TITLE
Another brb bug

### ISSUE THREAD

**Issue by ephemlw** [NickWildish/Mas-NSFW-Submod#83]
If you've been away for more than 30 minutes, Monika will disappear for a little while, but then will appear again.

1. Go to 'Be right back'
2. Click on 'I'm going to masturbate'
3. Wait for at least 30 minutes

Obviously, Monika shouldn't disappear after you've come back.
![screenshot0009](https://user-images.githubusercontent.com/104679049/178557515-2cb90661-2f21-4387-9cb1-fe715c707c30.png)

**Comment by ephemlw** [comment]
A few expression codes were misspelled and I fixed this little issue: [nsfw_brb.zip](https://github.com/NickWildish/Mas-NSFW-Submod/files/9598704/nsfw_brb.zip)
To install, go to NSFW Submod folder and replace the old file.

**Comment by NickWildish** [comment]
@ephemlw Thankyou for fixing this issue! It will be provided with the next update.

Leaving issue open so people have a temporary fix.

**Comment by NickWildish** [comment]
Added fix to latest update, so closing issue as resolved.
