### ISSUE TITLE
cant sext

### ISSUE THREAD

**Issue by tiredtree** [NickWildish/Mas-NSFW-Submod#84]
I'm able to say I'm horny but she only says "oh that must be so distracting"

**Comment by ephemlw** [comment]
Monika says that only when your last succesful sexting session was less than three hours ago, so I think that was done intentionally.

**Comment by tiredtree** [comment]
I have waited a few weeks sense the issue and she still responds the same way

**Comment by ephemlw** [comment]
I see. In that case this must be a bug. However, I'm not a mod dev, so I can't do much here.

**Comment by mizuotanu-nirera** [comment]
Are you able to sext by picking the options "Hey, Monika..." > "Sex" > "Do you want to sext?"

**Comment by tiredtree** [comment]
ahh yes. I restarted the game again and it worked this time. thank you guys for your help
