### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by xealmn** [NickWildish/Mas-NSFW-Submod#85]
So my account is over 18, I only got 2 unseen things, “I want to tell you something lewd….” And Monika telling me stories about the other girls, I excepted some more questions to ask her, do I need her to ask me?

**Comment by tiredtree** [comment]
if you go to the I feel... you should be able to say your horny

**Comment by NickWildish** [comment]
Most content within the submod requires the player to be 18+, but also to have at least 400 affection for most topics, and 1000 affection for the more risque options.

Closing issue as resolved.
