### ISSUE TITLE
Bug - wont update

### ISSUE THREAD

**Issue by MatthewAJohnson281** [NickWildish/Mas-NSFW-Submod#86]
**Describe the bug**
it wont update

**To Reproduce**
1. Go to submod updater
2. Click on update
3. Scroll down to '.
4. see it load forever

**Expected behavior**
I expected it to update

**Screenshots**

**Comment by ephemlw** [comment]
You can update it manually. Go here https://github.com/NickWildish/Mas-NSFW-Submod/releases/tag/1.2.0, download the mod and then replace the old version with the new one.

**Comment by NickWildish** [comment]
Closing issue as resolved.
