### ISSUE TITLE
why doesnt she have nipples?

### ISSUE THREAD

**Issue by MatthewAJohnson281** [NickWildish/Mas-NSFW-Submod#87]
**Describe the bug**
when I hold her with her clothes off I see that she is nipple less

**Comment by ephemlw** [comment]
Here are the sprites with nipples:
[b-20220504T122903Z-001.zip](https://github.com/NickWildish/Mas-NSFW-Submod/files/9274514/b-20220504T122903Z-001.zip)

To replace the original sprites, go to the game directory -> game -> mod assets -> monika -> b and merge files.

**Comment by MatthewAJohnson281** [comment]
Thank you!

**Comment by ephemlw** [comment]
You're welcome :)

**Comment by NickWildish** [comment]
Closing issue as resolved.
