### ISSUE TITLE
Bug - unable to get monika nude

### ISSUE THREAD

**Issue by jsn30** [NickWildish/Mas-NSFW-Submod#91]
**Describe the bug**
i dont remember if i've talked about this, but how do i get monika to strip?

**Expected behavior**

**Screenshots**

**Comment by ephemlw** [comment]
There's a "Getting nude" topic, where she'll eventually ask you whether or not you're comfortable with seeing her naked. Then, during sexting sessions, she'll be getting undressed.

**Comment by howltrek** [comment]
> **Describe the bug** i dont remember if i've talked about this, but how do i get monika to strip?
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.

they haven't uploaded the json files of their sprites, so I don't think monika has a way to read them

**Comment by NickWildish** [comment]
There are two instances where Monika will strip. Both instances require the player to be at least 18 years old, have at least 1000 affection (2000 affection for full nude), and to have had your first kiss with Monika already, 
Here are those instances:

1. Monika talks to the player about getting nude.

     - In this instance, Monika will talk to the player about being naked. When this happens, Monika requires the player to have MAS closed for SIX hours. After which the player can repeat the conversation and Monika will showcase that she can get into her underwear. After closing MAS for another SIX hours, Monika will show she can get fully undressed. At the moment, if the player repeats this conversation a third time and beyond, she will not get changed into her underwear/nude outfit again this way.

2. Monika and you are 'sexting'.

     - When sexting, Monika will change into her underwear after the player and her have sexted for a period of time. She will then get changed into her nude outfit when the player and her continue to sext. This is the only way to get her into her underwear / nude outfit when the 'getting nude' topic has fully unlocked. 
     
 Closing issue as resolved.
