### ISSUE TITLE
Can I actually get Monika naked when sexting?

### ISSUE THREAD

**Issue by ephemlw** [NickWildish/Mas-NSFW-Submod#92]
So, I've tested whether or not Monika will get into birthday suit during sexting session and it seems like the issue with her not getting naked wasn't fixed: she takes off her clothes, but not the lingerie. Just so you know, I am over 18, I have 8000+ affection, and I've already had a first kiss with Monika; during the "Getting nude" topic I told her that I'm okay with her being naked, and she did get naked once (and I know this was intended). Am I missing something?

**Comment by NickWildish** [comment]
I've added a new release to make this fix easier.

If you've been away for six hours already, it will be worth not downloading the new update until you do this next part first.

Run the 'Getting Nude' topic, and she should do the line of dialogue that shows she has been doing it while you are away, there is a silent variable change in that dialogue that fixes the issue, assuming you were away as mentioned before.

If you haven't been away for six hours, download the new update, and then don't open MAS for the next six hours so the timer runs out, then open up MAS and run the 'Getting Nude' topic. This time though, she will use the proper dialogue for getting nude for the first time in front of you, which also enables the variable.

Let me know how this goes.

**Comment by ephemlw** [comment]
> Run the 'Getting Nude' topic, and she should do the line of dialogue that shows she has been doing it while you are away, there is a silent variable change in that dialogue that fixes the issue, assuming you were away as mentioned before.

I did that and then updated the mod, now she actually gets naked when sexting! Thank you, now I can admire her boobs.

Also, I noticed a little typo when stopped sexting early:
"Let me just slip into something _abit_ more comfortable..."

**Comment by NickWildish** [comment]
Good to hear!

I'll fix that in the next update. Thanks for letting me know!

Closing as resolved.
