### ISSUE TITLE
Feature - Not changing a lingerie when Monika already wears one during sexting

### ISSUE THREAD

**Issue by ephemlw** [NickWildish/Mas-NSFW-Submod#94]
Right now, she changes anything to the lingerie that this mod adds and it's weird seeing her change one lingerie to another.

**Comment by NickWildish** [comment]
Just to clarify: right now in the mod, Monika should change into new lingerie every time you run a new sexting session. Is this behavior what you are experiencing or is it something else?

If this is the case, I think a better idea would be to add a boolean that allows the player to turn that particular feature ON or OFF depending on their preference.

**Comment by ephemlw** [comment]
Ok, I'll explain. Let's say Monika is wearing any lingerie available and then you start sexting. At some point, she changes it to the lingerie that this mod adds. And so it feels weird when she wears, for instance, bralette...
![screenshot0009](https://user-images.githubusercontent.com/104679049/196775606-f92303da-2e69-45fd-a6df-507f9ab00069.png)
...and then changes it to a white lingerie.
![screenshot0010](https://user-images.githubusercontent.com/104679049/196775736-7ca2353f-00cb-4601-acfc-94ef5520efdb.png)

**Comment by mizuotanu-nirera** [comment]
> Just to clarify: right now in the mod, Monika should change into new lingerie every time you run a new sexting session. Is this behavior what you are experiencing or is it something else?
> 
> If this is the case, I think a better idea would be to add a boolean that allows the player to turn that particular feature ON or OFF depending on their preference.

Yeah, the [check](https://github.com/NickWildish/Mas-NSFW-Submod/blob/01c944f110c1f6f6ca9bc7ecbaec0bec29cee177/game/Submods/NSFW%20Submod/nsfw_sexting.rpy#L47) to see if she's already wearing lingerie (`store.ahc_utils.isWearingClothesOfExprop("lingerie")`) only happens for players who have Auto Outfit Change installed - presumably this user doesn't use that one. My bad, I set it up wrong. We need to enclose 47-53 as well as 89-95 here in `if not store.ahc_utils.isWearingClothesOfExprop("lingerie"):` blocks that run that check. That way if she's already wearing lingerie then she won't change to a different one, regardless if that submod is mounted or not.

**Comment by ephemlw** [comment]
>presumably this user doesn't use that one. 

Yep, I don't have Auto Outfit Change.

**Comment by NickWildish** [comment]
This has been added to the latest update of the submod.

Monika will now remain in her current lingerie (assuming it has the 'lingerie' ex_prop applied) during the switch between cute and hot dialogue, as long as she is not unlocking any new underwear.

Closing issue as resolved.
